contradb/contra

app/assets/javascripts/libfigure/figure.es6, spec/helpers/dances_helper_spec.rb
https://github.com/dcmorse/contra/issues/128
=> introduce 'gyre meltdown' figure

app/assets/javascripts/libfigure/figure.es6, app/assets/stylesheets/figures.scss, app/controllers/figures_controller.rb, app/helpers/globo_helper.rb, app/models/dance.rb, app/views/about/index.html.erb, app/views/figures/_mdtab.html.erb, app/views/figures/index.html.erb, app/views/figures/show.html.erb, app/views/layouts/application.html.erb, app/views/programs/show.html.erb, app/views/welcome/index.html.erb, config/routes.rb, lib/jslibfigure.rb, lib/move.rb, spec/factories/dance.rb, spec/features/figures/index_spec.rb, spec/features/figures/show_spec.rb, spec/lib/jslibfigure_spec.rb, spec/lib/move_spec.rb, spec/models/dance_spec.rb
A lot of the functionality imagined for https://github.com/dcmorse/contra/issues/42
This is FiguresController, it adds a new menu item and analytics for understanding usage of figures in dances.
=> Figures controller

app/assets/javascripts/libfigure/figure.es6, app/assets/javascripts/libfigure/util.js, spec/helpers/dances_helper_spec.rb
=> add 'who' parameter to star promenade #143 - does not include migration

app/assets/javascripts/libfigure/figure.es6, spec/helpers/dances_helper_spec.rb
no dances need to be migrated. Woot.
=> To ocean wave

app/assets/javascripts/libfigure/param.js, app/views/dances/_chooser.html.erb, spec/helpers/dances_helper_spec.rb
https://github.com/dcmorse/contra/issues/207
=> change 'up & down the set' to 'along the set'

app/views/devise/registrations/edit.html.erb, spec/features/users/edit_spec.rb, spec/login_helper.rb
=> Fix issue #220 - can't edit username

app/assets/javascripts/welcome.js, app/views/welcome/index.html.erb, spec/features/welcome/index_spec.rb
=> Back button on filters fixes #221

app/assets/javascripts/libfigure/define-figure.js
hi dave. this is what we just did here.
=> move swing to top of move menu

app/assets/javascripts/dances.js, app/assets/javascripts/welcome.js, app/views/dances/_form.html.erb, spec/features/dances/create_spec.rb
=> 'Add Figure' and 'Remove Figure' buttons act on selected figure

app/assets/javascripts/dances.js, spec/features/dances/create_spec.rb
Insert new figure _after_ selection, not _before_.
=> Editor figure buttons 182

app/assets/javascripts/libfigure/define-figure.js
=> reverted moves and added movesMenuOrdering

Gemfile, app/assets/javascripts/dances.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/dances.scss, app/controllers/dances_controller.rb, app/models/dance.rb, app/views/choreographers/index.json.jbuilder, app/views/choreographers/show.json.jbuilder, app/views/dances/_bodyshow.html.erb, app/views/dances/_form.html.erb, app/views/dances/_markdown_advertisement.html.erb, app/views/dances/show.html.erb, app/views/dances/show.json.jbuilder, app/views/programs/index.json.jbuilder, app/views/programs/show.json.jbuilder, db/migrate/20171216025445_add_preamble_and_hook_to_dances.rb, db/schema.rb, spec/factories/dance.rb, spec/features/dances/copy_spec.rb, spec/features/dances/create_spec.rb, spec/features/dances/edit_spec.rb, spec/features/dances/show_spec.rb, spec/views/dances/show.html.erb_spec.rb
=> Preamble hook

Gemfile, Gemfile.lock
=> remove sqlite gem

README.md, app/views/about/index.html.erb, app/views/choreographers/show.html.erb, app/views/dances/_form.html.erb, app/views/welcome/index.html.erb, spec/features/welcome/index_spec.rb, spec/views/about/index.html.erb_spec.rb
I left one /dcmorse/contra in place because it was in a comment about where you filed an issue a long time ago.
=> dcmorse github path changed to contradb

app/assets/javascripts/libfigure/param.js, app/assets/javascripts/welcome.js, app/views/dances/_chooser.html.erb
added cozy line, cloverleaf, thread the needle, right hand high left hand low, and sliding doors as down the hall/up the hall enders. Not thrilled with the verb-phrase that goes with sliding doors (I chose something awful like "move into sliding doors formation" instead of the jauntier "slide those doors!"), maybe the bosses can think of something better.
=> added down the hall enders

app/assets/javascripts/libfigure/dance.js, app/assets/javascripts/libfigure/define-figure.js, app/assets/javascripts/libfigure/figure.es6, app/assets/javascripts/libfigure/move.js, app/assets/javascripts/libfigure/util.js, app/assets/javascripts/welcome.js, app/views/dances/_chooser.html.erb, spec/helpers/dances_helper_spec.rb
fix #315 box circulate & allemande orbit dialect bug
grandly unify dancerSubstitution and moveSubstitution arglists
tweak invertPair arglist
=> implement #210 arch & dive figure

app/assets/javascripts/libfigure/define-figure.js, app/assets/javascripts/libfigure/param.js, app/assets/javascripts/libfigure/util.js, app/views/dances/_bodyshow.html.erb, app/views/dances/_form.html.erb, app/views/dances/_markdown_advertisement.html.erb, app/views/dances/_markdown_dialect_advertisement.html.erb, app/views/dances/show.html.erb, lib/jslibfigure.rb, spec/features/dances/edit_spec.rb, spec/helpers/dances_helper_spec.rb, spec/lib/jslibfigure_spec.rb, spec/views/dances/show.html.erb_spec.rb
=> lightly translating the notes

Gemfile.lock, app/assets/javascripts/libfigure/figure.es6
when you check balance, the beats change to 8, giving you plenty of time to say "wheee!"  
Beats change back when unbalanced.
=> pull bys: beat changes when balance changes

app/assets/stylesheets/application.scss, app/controllers/dances_controller.rb, app/controllers/users/registrations_controller.rb, app/controllers/users_controller.rb, app/helpers/dances_helper.rb, app/models/user.rb, app/views/dances/show.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/users/index.html.erb, config/routes.rb, db/migrate/20180507223159_add_news_email_and_moderator_email_to_user.rb, db/schema.rb, spec/factories/users.rb, spec/features/dances/show_spec.rb, spec/features/users/create_spec.rb, spec/features/users/edit_spec.rb, spec/features/users/index_spec.rb
=> user notifications settings

app/assets/javascripts/libfigure/define-figure.js, app/assets/javascripts/libfigure/figure.es6, app/assets/javascripts/libfigure/param.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/dialects.scss, app/views/dances/_figure.html.erb, app/views/dances/_form.html.erb, app/views/dialects/index.html.erb, app/views/figures/show.html.erb, lib/jslibfigure.rb, spec/features/programs/show_spec.rb, spec/helpers/dances_helper_spec.rb, spec/lib/jslibfigure_spec.rb
=> %S shoulder round

app/assets/javascripts/dialect.js, app/assets/javascripts/libfigure/chooser.js, app/assets/javascripts/libfigure/define-figure.js, app/models/idiom/dancer.rb, db/migrate/20180519203858_add_ladle_and_gent_to_installed_dialects.rb, db/schema.rb, spec/features/dialect/index_spec.rb
=> ladle and gentlespoon

app/assets/javascripts/libfigure/define-figure.js, app/assets/javascripts/libfigure/figure.es6, app/assets/javascripts/libfigure/test.js, app/assets/javascripts/libfigure/words.js, app/views/dances/_bodyshow.html.erb, lib/jslibfigure.rb, spec/features/dances/show_spec.rb, spec/lib/jslibfigure_spec.rb
=> Lingo Lines Markdown bug

app/views/dances/_chooser.html.erb, spec/features/programs/delete_spec.rb, spec/models/program_spec.rb, sysadmin/cloud/contradb-backup, sysadmin/laptop/contradb-backup
=> bulk deploy

app/assets/javascripts/libfigure/define-figure.js, app/assets/javascripts/libfigure/test.js, app/assets/javascripts/libfigure/util.js, app/assets/javascripts/libfigure/words.js, lib/dialect_reverser.rb, spec/features/dances/edit_spec.rb, spec/helpers/dances_helper_spec.rb, spec/lib/dialect_reverser_spec.rb
=> non-urgent dialect and lingo-line issues

app/assets/javascripts/libfigure/figure.es6, spec/helpers/dances_helper_spec.rb
=> new figure revolving door - resolve #417

app/assets/javascripts/welcome.js, app/views/welcome/index.html.erb, spec/features/welcome/index_spec.rb
to Created(desc) from Updated(desc) - resolves #352
=> change main page default display order 

spec/features/dances/delete_spec.rb, spec/features/programs/copy_spec.rb, spec/features/programs/delete_spec.rb, spec/lib/dialect_reverser_spec.rb, spec/lib/jslibfigure_spec.rb
=> Parenthesize the first (name) argument to let and let! calls in specs

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/dances.js, app/assets/stylesheets/application.scss, app/views/dances/_bodyshow.html.erb, app/views/dances/_validation_toggle.html.erb, app/views/dances/show.html.erb, app/views/programs/show.html.erb, spec/factories/dance.rb, spec/features/dances/show_js_spec.rb, spec/features/dialect/index_spec.rb, spec/features/programs/show_js_spec.rb
=> validation toggle (basic)

app/assets/javascripts/libfigure/figure.es6, spec/helpers/dances_helper_spec.rb
Revert "Revert "remove talk of progression from 'slide left' figure - resolves #476""
This reverts commit 8476a0663046a196945cfe6309ec6287fc5b216c.
=> slide left - remove "to new neighbor" language

app/assets/stylesheets/application.scss
=> hack firefox to display select boxes properly - temporarily fixes #522

app/assets/javascripts/dances.js, app/assets/javascripts/libfigure/define-figure.js, app/assets/javascripts/libfigure/words.js, db/migrate/20181107035156_progress_to_custom.rb, db/schema.rb
#474 
Also temporarily allows 'progress' back in the menu. For a very brief time.
=> migrate existing progress figures to custom

app/assets/javascripts/welcome.js, spec/features/welcome/index_spec.rb
=> progression reload bug

app/controllers/api/v1/dances_controller.rb, app/javascript/advanced-search.tsx, app/javascript/dance-table.tsx, app/javascript/ez-checkbox-filter.tsx, app/javascript/filter.ts, config/initializers/devise.rb, lib/filter_dances.rb, package.json, spec/controllers/users_controller_spec.rb, spec/features/welcome/index_spec.rb, spec/features/welcome/search_spec.rb, spec/javascript/advanced-search.spec.tsx, spec/requests/api/v1/dances_controller_spec.rb, yarn.lock
=> verified checkboxes for advanced search

app/javascript/advanced-search.tsx, app/javascript/ez-checkbox-filter.tsx, app/javascript/ez-query-helpers.ts, app/javascript/filter.ts, lib/filter_dances.rb, spec/features/welcome/search_spec.rb, spec/javascript/advanced-search.spec.tsx, spec/javascript/ez-query-helpers.spec.ts, spec/javascript/ez-query-helpers.spec.tsx, spec/lib/filter_dances_spec.rb
implements #620 , currently without the ["Option 4 warning"](https://github.com/contradb/contra/issues/620#issuecomment-583415955).
=> 'shared' ezfilter section

app/javascript/search-ex-clipboard.ts, app/javascript/search-ex-editor.tsx, lib/filter_dances.rb, spec/features/welcome/search_ex_spec.rb
implements #636, more or less
TODO: make sure you can't cross the streams with NumericSearchEx! [done]
=> Searchex copy paste

.github/workflows/rspec.yml, .github/workflows/test.yml
=> GitHub actions

sysadmin/cloud/contradb-backup, sysadmin/laptop/contradb-backup
=> port old backup script to terraform
